// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdf} from '../models';

export function CompressPDF(arg1:string,arg2:string,arg3:string):Promise<pdf.ToolResult>;

export function ImagesToPDF(arg1:Array<string>,arg2:string):Promise<pdf.ToolResult>;

export function MergePDFs(arg1:Array<string>,arg2:string):Promise<pdf.ToolResult>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PDFToImages(arg1:string,arg2:string,arg3:number,arg4:string):Promise<pdf.ToolResult>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectFiles(arg1:string):Promise<Array<string>>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function SplitPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<pdf.ToolResult>;
