// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompressPDF'](arg1, arg2, arg3);
}

export function ImagesToPDF(arg1, arg2) {
  return window['go']['main']['App']['ImagesToPDF'](arg1, arg2);
}

export function MergePDFs(arg1, arg2) {
  return window['go']['main']['App']['MergePDFs'](arg1, arg2);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PDFToImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PDFToImages'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function SplitPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SplitPDF'](arg1, arg2, arg3, arg4);
}
